-- BOZO v4.11.8 — Puzzle run review persistence
-- Stores compact puzzle-by-puzzle detail for signed-in Rush/Survival runs.
-- Run summaries remain in puzzle_runs. Detailed items are intentionally small:
-- FEN + result + compact move arrays. No engine caches or screenshots are stored.

create table if not exists public.puzzle_run_items (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.puzzle_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_index integer not null check (item_index >= 0),
  fen text not null,
  result text not null default 'unknown' check (result in ('solved','failed','unfinished','unknown')),
  attempted_move text,
  played_line jsonb not null default '[]'::jsonb,
  solution_pv jsonb not null default '[]'::jsonb,
  motif text,
  hint_used boolean not null default false,
  created_at timestamptz not null default now(),
  unique(run_id,item_index)
);

create index if not exists puzzle_run_items_run_idx on public.puzzle_run_items(run_id,item_index);
create index if not exists puzzle_run_items_user_idx on public.puzzle_run_items(user_id,created_at desc);

alter table public.puzzle_run_items enable row level security;

drop policy if exists "Users can read own puzzle run items" on public.puzzle_run_items;
create policy "Users can read own puzzle run items"
on public.puzzle_run_items for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own puzzle run items" on public.puzzle_run_items;
create policy "Users can insert own puzzle run items"
on public.puzzle_run_items for insert to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.puzzle_runs r
    where r.id = run_id and r.user_id = auth.uid()
  )
);

grant select, insert on public.puzzle_run_items to authenticated;
grant usage, select on sequence public.puzzle_run_items_id_seq to authenticated;

-- Keep all lightweight run summaries, but retain detailed puzzle-by-puzzle data
-- only for the newest 25 runs per user per mode. This bounds storage while leaving
-- long-term scores/history intact.
create or replace function public.prune_old_puzzle_run_details()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.puzzle_run_items pri
  using public.puzzle_runs old_run
  where pri.run_id = old_run.id
    and old_run.user_id = new.user_id
    and old_run.mode = new.mode
    and old_run.id in (
      select id from public.puzzle_runs
      where user_id = new.user_id and mode = new.mode
      order by created_at desc
      offset 25
    );
  return new;
end;
$$;

drop trigger if exists puzzle_runs_prune_detail_trigger on public.puzzle_runs;
create trigger puzzle_runs_prune_detail_trigger
after insert on public.puzzle_runs
for each row execute function public.prune_old_puzzle_run_details();
