-- BOZO v4.15.6: canonical theoretical endgame curriculum + searchable aliases.
-- Safe to run more than once: each seed row is guarded by title + FEN.

alter table public.endgame_positions
  add column if not exists search_aliases text not null default '';

with seed(title,category,subcategory,concept,fen,source_type,min_elo,max_elo,difficulty,objective,coach_intro,coach_lesson,search_aliases) as (
values
('Rule of the Square','Pawn','King and pawn fundamentals','Judge whether a king can catch a passed pawn without calculating every move.','8/8/8/8/4P3/8/8/k6K w - - 0 1','theory',500,1600,'Fundamentals','tablebase','This lesson is about the rule of the square: picture a square from the pawn to promotion and ask whether the defending king can enter it.','Do not race automatically. First decide whether the king can catch the pawn, then choose between pushing and bringing your king closer.','rule square passed pawn pawn race catch pawn king pawn basic conversion fundamentals'),
('Direct Opposition','Pawn','Opposition','Use opposition to force the enemy king to give ground and reach the key squares.','8/8/4k3/8/4K3/4P3/8/8 b - - 0 1','theory',700,1800,'Fundamentals','tablebase','This is direct opposition. The kings face each other with one square between them, so the side to move must yield ground.','Opposition is not the final goal. Use it to penetrate toward the pawn''s key squares.','opposition direct opposition kings king pawn zugzwang key squares pawn ending'),
('Key Squares','Pawn','King and pawn fundamentals','Reach the critical squares that guarantee promotion regardless of whose move it is.','8/8/4k3/3K4/3P4/8/8/8 w - - 0 1','theory',800,1800,'Beginner','tablebase','This lesson is about key squares. Your king, not the pawn, usually has to lead the conversion.','Ask which squares in front of the pawn guarantee promotion. Opposition is useful only when it helps the king reach one of them.','key squares critical squares king pawn opposition promotion pawn ending'),
('Wrong Bishop and Rook Pawn','Minor Piece','Bishop endings','Recognize the classic fortress when the bishop cannot control the rook pawn''s promotion corner.','k7/P7/1K6/2B5/8/8/8/8 w - - 0 1','theory',1000,2200,'Beginner','tablebase','Material says White is ahead, but this is the wrong-bishop rook-pawn fortress. The bishop cannot control the promotion corner.','If the defending king reaches the corner opposite the bishop''s color, the extra bishop may be useless. Watch for stalemate as well as promotion.','wrong bishop wrong colored bishop rook pawn fortress bishop pawn corner stalemate draw'),
('Réti Maneuver','Pawn','Pawn races','Use diagonal king movement to chase one pawn while supporting your own.','7K/8/k1P5/7p/8/8/8/8 w - - 0 1','theory',1200,2200,'Intermediate','tablebase','This is Réti''s famous pawn study. The king appears too far from both jobs, but diagonal movement lets it chase one pawn while approaching the other.','In pawn races, a king can pursue two goals at once. Look for diagonal routes that enter the enemy pawn''s square while supporting your own passer.','reti réti maneuver reti study pawn race diagonal king geometry famous study'),
('Bishop and Knight Checkmate','Minor Piece','Basic checkmates','Coordinate bishop, knight, and king to drive the bare king into the correct corner.','7k/8/2B1KN2/8/8/8/8/8 w - - 0 1','theory',1300,2400,'Intermediate','tablebase','This is bishop-and-knight mate. The hard part is not the final mating pattern but herding the king toward a corner controlled by your bishop.','Use your king to take space, the knight to cover the opposite color, and the bishop to build a shrinking box.','bishop knight mate b+n mate bn mate basic checkmate w maneuver triangle minor piece'),
('Philidor Position','Rook','Rook and pawn vs rook','Hold the draw with the third-rank defense, then check from behind after the pawn advances.','8/4k3/r7/4PK2/8/8/8/4R3 b - - 0 1','theory',1400,2400,'Club','tablebase','This is the Philidor position, the essential defensive setup in rook and pawn versus rook.','Keep the attacking king from crossing your defensive rank. Only after the pawn advances should the rook drop behind and begin checking.','philidor third rank defense sixth rank rook pawn rook vs rook drawing technique defensive rook ending'),
('Lucena Position','Rook','Rook and pawn vs rook','Build a bridge so the king can escape side checks and the pawn can promote.','4K3/2k1P3/8/8/8/8/5r2/6R1 w - - 0 1','theory',1500,2500,'Club','tablebase','This is the Lucena position, the fundamental winning rook-and-pawn ending.','Your king is in front of the pawn, but side checks stop it from stepping out. Build a bridge with the rook so the king can hide from checks and release the pawn.','lucena bridge building build a bridge rook pawn rook vs rook winning technique theoretical rook ending'),
('Vancura Position','Rook','Rook-pawn defenses','Draw against an advanced rook pawn by checking from the side while keeping the rook active.','R7/6k1/P4r2/1K6/8/8/8/8 b - - 0 1','theory',1800,2600,'Advanced','tablebase','This is the Vancura position, a key drawing method against an advanced rook pawn.','Do not become passive behind the pawn. Side checks and lateral rook activity keep the attacking king from finding shelter.','vancura rook pawn defense side checks lateral checks rook ending draw advanced rook pawn'),
('Queen vs Seventh-Rank Pawn','Queen','Queen vs pawn','Use checks and king approach carefully against a pawn one step from promotion.','8/4P3/8/8/8/8/6K1/7q b - - 0 1','theory',1800,2600,'Advanced','tablebase','A pawn on the seventh rank changes queen technique completely. Checks alone are not enough; the king often has to approach at the right moment.','Keep checking with a purpose: force the pawn''s king away or gain time for your own king to approach without allowing promotion.','queen vs pawn seventh rank queen pawn promotion advanced checks king approach'),
('Queen vs Rook: Precision Conversion','Queen','Queen vs rook','Force the rook away from its king, create zugzwang, and win it with a fork or mating net.','8/8/8/8/8/4KQ2/6rk/8 w - - 0 1','theory',2300,3000,'Master','tablebase','Queen versus rook is theoretically winning but notoriously difficult against accurate defense.','Do not chase the rook with meaningless checks. Improve the king, restrict the rook, create zugzwang, then use a checking fork when the rook is forced away from its king.','queen vs rook queen versus rook master pawnless endgame zugzwang fork third rank defense precision conversion'),
('Lolli Position: Rook and Bishop vs Rook','Rook','Rook and bishop vs rook','Dominate the defending rook and coordinate rook, bishop, and king to force the king toward the edge.','1r6/8/8/8/2B5/2K5/6R1/2k5 b - - 0 1','theory',2400,3000,'Master','tablebase','This is the Lolli position from the difficult rook-and-bishop versus rook ending.','The win depends on domination rather than a quick tactic. Coordinate the bishop and rook so checks run out and the defending rook loses useful squares.','lolli rook bishop vs rook rook and bishop versus rook master pawnless endgame domination theoretical'),
('Réti-Dedrle Pawn Tempo Study','Pawn','Triangulation and tempi','Use a waiting move and king route to win a pawn race that direct play only draws.','8/8/5k2/8/p7/8/1PK5/8 w - - 0 1','theory',2000,2800,'Expert','tablebase','This is a precise pawn-tempo study. The obvious king route draws; the winning route preserves a critical reserve tempo.','In pure pawn endings, count spare pawn moves and king tempi as resources. A waiting move can change who is forced to give way.','reti dedrle pawn tempo waiting move triangulation reserve tempo pawn ending expert')
)
insert into public.endgame_positions
(title,category,subcategory,concept,fen,source_type,min_elo,max_elo,difficulty,objective,coach_intro,coach_lesson,published,owner_verified,search_aliases)
select s.title,s.category,s.subcategory,s.concept,s.fen,s.source_type,s.min_elo,s.max_elo,s.difficulty,s.objective,s.coach_intro,s.coach_lesson,true,true,s.search_aliases
from seed s
where not exists (
  select 1 from public.endgame_positions e
  where lower(e.title)=lower(s.title) and e.fen=s.fen
);

create index if not exists endgame_positions_source_type_idx on public.endgame_positions(source_type);
create index if not exists endgame_positions_difficulty_idx on public.endgame_positions(difficulty);
