-- BOZO v4.15.7: expanded theoretical endgame curriculum.
-- Seeds 52 researched concept families and generates board-symmetry/file-shift training variants.
-- No side-to-move-only flips are used; generated variants preserve the chess geometry of the base study.

alter table public.endgame_positions add column if not exists concept_key text;
alter table public.endgame_positions add column if not exists variant_no integer;
alter table public.endgame_positions add column if not exists curriculum_order integer;
create index if not exists endgame_positions_concept_key_idx on public.endgame_positions(concept_key);

create or replace function pg_temp.bozo_expand_rank(r text) returns text language plpgsql as $$
declare out text=''; ch text; i int;
begin for i in 1..char_length(r) loop ch:=substr(r,i,1); if ch ~ '^[1-8]$' then out:=out||repeat('.',ch::int); else out:=out||ch; end if; end loop; return out; end $$;
create or replace function pg_temp.bozo_compress_rank(r text) returns text language plpgsql as $$
declare out text=''; n int=0; ch text; i int;
begin for i in 1..char_length(r) loop ch:=substr(r,i,1); if ch='.' then n:=n+1; else if n>0 then out:=out||n::text; n:=0; end if; out:=out||ch; end if; end loop; if n>0 then out:=out||n::text; end if; return out; end $$;
create or replace function pg_temp.bozo_swap_case(s text) returns text language plpgsql as $$
declare out text=''; ch text; i int;
begin for i in 1..char_length(s) loop ch:=substr(s,i,1); if ch ~ '^[A-Z]$' then out:=out||lower(ch); elsif ch ~ '^[a-z]$' then out:=out||upper(ch); else out:=out||ch; end if; end loop; return out; end $$;
create or replace function pg_temp.bozo_fen_variant(f text, kind text) returns text language plpgsql as $$
declare parts text[]:=regexp_split_to_array(f,' '); ranks text[]:=string_to_array(parts[1],'/'); rr text[]:=array[]::text[]; e text; i int; side text:=parts[2];
begin if kind in ('rot','vflip') then side:=case side when 'w' then 'b' else 'w' end; end if; if kind='id' then rr:=ranks; elsif kind='mirror' then for i in 1..8 loop e:=reverse(pg_temp.bozo_expand_rank(ranks[i])); rr:=array_append(rr,pg_temp.bozo_compress_rank(e)); end loop; elsif kind='rot' then for i in reverse 8..1 loop e:=reverse(pg_temp.bozo_expand_rank(ranks[i])); e:=pg_temp.bozo_swap_case(e); rr:=array_append(rr,pg_temp.bozo_compress_rank(e)); end loop; elsif kind='vflip' then for i in reverse 8..1 loop e:=pg_temp.bozo_expand_rank(ranks[i]); e:=pg_temp.bozo_swap_case(e); rr:=array_append(rr,pg_temp.bozo_compress_rank(e)); end loop; else rr:=ranks; end if; return array_to_string(rr,'/')||' '||side||' - - 0 1'; end $$;
create or replace function pg_temp.bozo_shift_fen(f text, delta int) returns text language plpgsql as $$
declare parts text[]:=regexp_split_to_array(f,' '); ranks text[]:=string_to_array(parts[1],'/'); rr text[]:=array[]::text[]; e text; i int; d int:=abs(delta);
begin if delta=0 then return f; end if; for i in 1..8 loop e:=pg_temp.bozo_expand_rank(ranks[i]); if delta>0 then if right(e,d)<>repeat('.',d) then return null; end if; e:=repeat('.',d)||left(e,8-d); else if left(e,d)<>repeat('.',d) then return null; end if; e:=right(e,8-d)||repeat('.',d); end if; rr:=array_append(rr,pg_temp.bozo_compress_rank(e)); end loop; return array_to_string(rr,'/')||' '||parts[2]||' - - 0 1'; end $$;

delete from public.endgame_positions where source_type='theory';
create temporary table bozo_endgame_seed(concept_key text,title text,category text,subcategory text,concept text,fen text,min_elo int,max_elo int,difficulty text,coach_intro text,coach_lesson text,search_aliases text,sort_no int) on commit drop;
insert into bozo_endgame_seed values
('rule-square','Rule of the Square','Pawn','King and pawn fundamentals','Judge whether the defending king can catch a passed pawn without calculating every move.','8/8/8/8/4P3/8/8/k6K w - - 0 1',500,1600,'Fundamentals','Picture the pawn’s square before calculating.','If the king can enter the square in time, the pawn cannot simply run. Use this shortcut before spending moves on calculation.','rule square passed pawn race catch pawn basic',1),
('direct-opposition','Direct Opposition','Pawn','Opposition','Use direct opposition to force the enemy king to yield ground.','8/8/4k3/8/4K3/4P3/8/8 b - - 0 1',700,1800,'Fundamentals','The kings are facing each other. Decide who is forced to give way.','Opposition is a means to reach key squares. Do not take it mechanically if another king move wins faster.','opposition direct kings zugzwang key squares',2),
('distant-opposition','Distant Opposition','Pawn','Opposition','Use an odd number of squares between the kings to preserve the opposition from farther away.','8/8/3k4/8/8/3K4/3P4/8 w - - 0 1',900,1900,'Beginner','This is opposition from a distance rather than face to face.','Count the files and ranks between the kings. Distant opposition often decides who gets the direct opposition later.','distant opposition corresponding kings pawn',3),
('diagonal-opposition','Diagonal Opposition','Pawn','Opposition','Use diagonal king geometry to transpose into direct opposition on favorable terms.','8/8/5k2/8/3K4/3P4/8/8 w - - 0 1',1000,2000,'Beginner','The kings are offset diagonally. Your route determines who gets the next opposition.','Diagonal opposition matters because king moves can transpose into direct opposition while approaching the key squares.','diagonal opposition kings geometry pawn',4),
('key-squares','Key Squares','Pawn','King and pawn fundamentals','Reach the critical squares that guarantee promotion.','8/8/4k3/3K4/3P4/8/8/8 w - - 0 1',800,1800,'Beginner','Identify the key squares before pushing the pawn.','The king normally has to lead. A pawn push that gives up access to the key squares can throw away the win.','key squares critical squares king pawn promotion',5),
('king-front','King in Front of the Pawn','Pawn','King and pawn fundamentals','Use the king as a shield so the pawn can advance safely.','8/8/4k3/4P3/4K3/8/8/8 w - - 0 1',900,1900,'Beginner','The king is the strongest escort for a passed pawn.','Keep the king in front when possible. The pawn should support the king’s progress, not block it.','king in front pawn escort promotion',6),
('rook-pawn-exception','Rook Pawn Exception','Pawn','King and pawn fundamentals','Recognize when an edge pawn draws because the defending king reaches the corner.','8/8/8/8/P7/K7/8/k7 w - - 0 1',1000,2100,'Beginner','Rook pawns behave differently because there is no space beyond the edge of the board.','Do not apply central-pawn key-square rules blindly to rook pawns. The corner often gives the defender a fortress.','rook pawn edge pawn corner draw exception',7),
('reserve-tempo','Reserve Tempo','Pawn','Pawn tempi','Save a pawn move so the opponent is forced to move the king first.','8/8/4k3/3p4/3P4/4K3/6P1/8 w - - 0 1',1200,2200,'Intermediate','One apparently useless pawn move may be your most valuable resource.','Count spare pawn moves as tempi. A reserve tempo can transfer the move and create zugzwang.','reserve tempo spare pawn move waiting move zugzwang',8),
('triangulation','Triangulation','Pawn','Zugzwang and tempi','Lose a tempo with the king so the opponent must move in the critical position.','8/8/4k3/8/3PK3/8/8/8 w - - 0 1',1300,2300,'Intermediate','The goal is to return to the same setup with the other side to move.','Triangulation is controlled tempo loss. Use a three-square king route when a direct move would give the opponent the opposition.','triangulation tempo zugzwang king route',9),
('breakthrough','Pawn Breakthrough','Pawn','Pawn races','Sacrifice pawns to create a passer that cannot be stopped.','8/8/2pp4/8/2PP4/8/4K3/7k w - - 0 1',1100,2200,'Intermediate','Do not count pawns only by material. Sometimes one pawn is worth sacrificing to free another.','Look for forcing captures that create an outside passer or a pawn that reaches promotion first.','pawn breakthrough sacrifice passer connected pawns',10),
('protected-passer','Protected Passed Pawn','Pawn','Passed pawns','Use a protected passer to tie down the enemy king while your king attacks elsewhere.','8/8/4k3/3pP3/3P4/8/4K3/8 w - - 0 1',1200,2200,'Intermediate','A protected passer can act like an extra piece because the king may be unable to abandon it.','Use the passer to restrict the enemy king, then improve your king rather than pushing automatically.','protected passed pawn passer king restriction',11),
('outside-passer','Outside Passed Pawn','Pawn','Passed pawns','Use a distant passer to drag the enemy king away from the other wing.','8/8/3k4/p6P/3p4/3P4/4K3/8 w - - 0 1',1300,2300,'Intermediate','The distant passer matters because it stretches the defending king.','Create the outside passer, force the king toward it, then use your king on the opposite side.','outside passed pawn distant passer diversion',12),
('reti','Réti Maneuver','Pawn','Pawn races','Use diagonal king movement to chase one pawn while supporting your own.','7K/8/k1P5/7p/8/8/8/8 w - - 0 1',1200,2200,'Intermediate','The king can pursue two goals at once by moving diagonally.','Enter the enemy pawn’s square while approaching your own passer. Geometry matters more than raw distance.','reti réti maneuver famous study pawn race diagonal king',13),
('corresponding-squares','Corresponding Squares','Pawn','Zugzwang and tempi','Match king squares so every enemy king move has a precise answer.','8/8/3k4/3p4/2pP4/2P1K3/8/8 w - - 0 1',2000,2800,'Expert','This position is about matching squares rather than a single opposition.','Identify pairs of corresponding king squares. Moving to the wrong member of the network can lose a tempo permanently.','corresponding squares mined squares pawn endgame expert zugzwang',14),
('advanced-triangulation','Advanced Triangulation','Pawn','Zugzwang and tempi','Use multiple king routes and reserve tempi to force the opponent into zugzwang.','8/8/3k4/2pP4/2P5/4K3/6P1/8 w - - 0 1',2100,2900,'Expert','There are several candidate king routes, but only the tempo count matters.','Compare routes by move parity and reserve pawn tempi, not just by geometric distance.','advanced triangulation reserve tempi zugzwang pawn expert',15),
('queen-mate','Queen Checkmate Technique','Queen','Basic checkmates','Use the queen to box in the king, then bring your king up to mate.','8/8/8/8/4K3/4Q3/8/7k w - - 0 1',500,1500,'Fundamentals','First make the enemy king’s box smaller, then bring your king closer.','Avoid stalemate. The queen restricts; your king supplies the final support.','queen mate basic checkmate box king stalemate',16),
('rook-mate','Rook Checkmate Technique','Rook','Basic checkmates','Use the rook and king to drive the enemy king to the edge.','8/8/8/8/4K3/8/6R1/7k w - - 0 1',500,1500,'Fundamentals','The rook cuts off ranks and files while your king closes the box.','Keep the rook protected from king attacks and shrink the available space step by step.','rook mate basic checkmate box king',17),
('two-bishops','Two Bishops Checkmate','Minor Piece','Basic checkmates','Coordinate both bishops and king to drive the enemy king to an edge.','8/8/8/4K3/8/3BB3/8/7k w - - 0 1',1000,2100,'Beginner','The bishops create a diagonal wall; the king does the pushing.','Keep the bishops coordinated so the enemy king cannot slip through opposite-colored squares.','two bishops mate bishop pair basic checkmate',18),
('bn-mate','Bishop and Knight Checkmate','Minor Piece','Basic checkmates','Coordinate bishop, knight, and king to force the bare king into the correct corner.','7k/8/2B1KN2/8/8/8/8/8 w - - 0 1',1300,2400,'Intermediate','The hard part is herding the king toward a corner controlled by your bishop.','Use the king to take space, the knight to cover the opposite color, and the bishop to shrink the box.','bishop knight mate bn mate w maneuver minor piece',19),
('wrong-bishop','Wrong Bishop and Rook Pawn','Minor Piece','Bishop endings','Recognize the fortress when the bishop cannot control the promotion corner.','k7/P7/1K6/2B5/8/8/8/8 w - - 0 1',1000,2200,'Beginner','Material is not enough when the bishop cannot control the rook pawn’s corner.','If the defending king reaches the wrong-colored corner, the extra bishop may be unable to force promotion.','wrong bishop rook pawn fortress corner draw',20),
('bishop-pawn','Bishop vs Pawn','Minor Piece','Bishop endings','Coordinate bishop and king to stop or support a dangerous passed pawn.','8/8/4k3/3p4/8/3B4/4K3/8 w - - 0 1',1100,2200,'Intermediate','A bishop can stop a pawn from far away, but only on one color complex.','Before moving the bishop, check whether the pawn can step onto a square the bishop can no longer control.','bishop vs pawn stopper blockade minor piece',21),
('knight-pawn','Knight vs Pawn','Minor Piece','Knight endings','Use knight geometry and king support to blockade a passed pawn.','8/8/4k3/3p4/8/3N4/4K3/8 w - - 0 1',1200,2300,'Intermediate','Knights are excellent blockaders but poor at stopping distant rook pawns.','Find a stable blockade square first, then bring the king into the fight.','knight vs pawn blockade minor piece',22),
('opposite-bishops','Opposite-Colored Bishop Fortress','Minor Piece','Bishop endings','Build or break a fortress when each bishop controls a different color complex.','8/8/3k4/3p4/3P4/2B2b2/6K1/8 w - - 0 1',1500,2500,'Club','Opposite-colored bishops make it difficult to challenge the defender’s blockade directly.','Create passed pawns on both wings if attacking; if defending, anchor pawns on squares your bishop controls.','opposite colored bishops fortress draw bishop ending',23),
('same-bishops','Same-Colored Bishop Conversion','Minor Piece','Bishop endings','Improve king activity and attack fixed pawns in same-colored bishop endings.','8/8/3k4/3p4/3P4/2B5/5bK1/8 b - - 0 1',1500,2500,'Club','Same-colored bishops fight over the same weaknesses, so king activity matters enormously.','Fix pawns on the color of the bishops, activate the king, and create a second weakness before trading.','same colored bishops conversion two weaknesses',24),
('bishop-knight','Bishop vs Knight Technique','Minor Piece','Bishop vs knight','Use pawn structure and king activity to exploit the strengths of bishop or knight.','8/8/3k4/3p4/3P4/2B5/5nK1/8 w - - 0 1',1600,2600,'Club','The right minor piece depends on the pawn structure and available outposts.','Open both wings for the bishop; build stable outposts and closed squares for the knight.','bishop vs knight minor piece technique outpost color complex',25),
('rook-behind-passer','Rook Behind the Passed Pawn','Rook','Rook principles','Place the rook behind a passed pawn so every pawn move increases the rook’s range.','8/8/4k3/4P3/8/4K3/8/R6r w - - 0 1',1200,2300,'Intermediate','Rooks usually work best behind passed pawns, whether attacking or defending them.','From behind, the rook gains checking and attacking distance as the pawn advances.','rook behind passed pawn tarrasch rule rook ending',26),
('rook-vs-pawn-cutoff','Rook vs Pawn: Cut Off the King','Rook','Rook vs pawn','Separate the king from its pawn so the rook can stop promotion.','8/8/4k3/4p3/8/4K3/8/R7 w - - 0 1',1100,2200,'Intermediate','The rook does not need to chase the pawn immediately if it can cut the king off.','Cut the king first, then approach with your king or attack the pawn from behind.','rook vs pawn cut off king stop promotion',27),
('checking-distance','Checking Distance','Rook','Rook defense','Keep enough files or ranks between the rook and king to check safely.','8/8/4k3/4P3/4K3/8/8/R6r b - - 0 1',1400,2400,'Club','Checks work only if the rook has enough distance to avoid being chased.','Maintain checking distance and choose the long side whenever possible.','checking distance rook checks long side defense',28),
('short-side','Short-Side Defense','Rook','Rook defense','Put the king on the short side and the rook on the long side for checking room.','8/8/4k3/4P3/4K3/8/r7/6R1 b - - 0 1',1600,2600,'Club','The defending king belongs on the short side so the rook has the long side for checks.','Count files. The rook needs maximum checking distance and should not be trapped by the attacking king.','short side defense long side rook checks',29),
('side-checks','Side-Check Defense','Rook','Rook defense','Use lateral checks to stop the king from sheltering in front of the pawn.','8/8/4k3/4P3/4K3/8/7r/R7 b - - 0 1',1600,2600,'Club','Side checks can hold positions that passive defense loses.','Keep enough horizontal distance and avoid allowing the attacking king to approach your rook with tempo.','side checks lateral checks rook defense',30),
('frontal-defense','Frontal Rook Defense','Rook','Rook defense','Check from the front when the defending king cannot reach the ideal setup.','4r3/8/4k3/4P3/4K3/8/8/4R3 b - - 0 1',1700,2700,'Advanced','A rook in front of the pawn can sometimes hold by checking along the file.','The exact checking distance matters. If the attacking king gets too close, frontal checks stop working.','frontal rook defense front checks rook ending',31),
('lucena','Lucena Position','Rook','Rook and pawn vs rook','Build a bridge so the king can escape checks and the pawn can promote.','4K3/2k1P3/8/8/8/8/5r2/6R1 w - - 0 1',1500,2500,'Club','This is the fundamental winning rook-and-pawn setup.','Build a bridge with the rook so the king can hide from side checks and release the pawn.','lucena bridge building rook pawn theoretical rook ending',32),
('reaching-lucena','Reaching the Lucena','Rook','Rook and pawn vs rook','Convert an earlier rook ending into the Lucena setup.','8/4k3/4P3/4K3/8/8/6r1/5R2 w - - 0 1',1700,2700,'Advanced','Knowing Lucena is not enough; you also need to recognize how to reach it.','Cut the king, advance without allowing checks from behind, and aim for king-in-front plus rook bridge geometry.','reaching lucena transition rook endgame',33),
('philidor','Philidor Position','Rook','Rook and pawn vs rook','Hold the draw with the third-rank defense, then check from behind.','8/4k3/r7/4PK2/8/8/8/4R3 b - - 0 1',1400,2400,'Club','This is the essential defensive setup in rook and pawn versus rook.','Keep the attacking king off the sixth rank. After the pawn advances, switch to checking from behind.','philidor third rank defense sixth rank rook draw',34),
('avoiding-philidor','Avoiding the Philidor','Rook','Rook and pawn vs rook','Prevent the defender from establishing the standard Philidor drawing setup.','8/4k3/8/r3P3/4K3/8/8/4R3 w - - 0 1',1700,2700,'Advanced','The defender is trying to reach a known drawing setup.','Use king placement and rook activity to deny the third-rank defense before pushing the pawn.','avoid philidor prevent philidor rook winning technique',35),
('vancura','Vancura Position','Rook','Rook-pawn defenses','Draw against an advanced rook pawn by checking from the side.','R7/6k1/P4r2/1K6/8/8/8/8 b - - 0 1',1800,2700,'Advanced','The rook stays active from the side instead of sitting passively behind the pawn.','Use lateral checks and attack the pawn whenever the king loses shelter.','vancura rook pawn defense side checks advanced',36),
('rook-pawn-seventh','Seventh-Rank Rook Pawn','Rook','Rook-pawn endings','Handle the special geometry of an advanced rook pawn with active rook placement.','R7/7P/6K1/8/8/6k1/8/7r w - - 0 1',1800,2800,'Advanced','Rook pawns remove one side of the board, so normal rook-ending rules change.','Check whether the attacking king has shelter and whether the defending rook can check from the side.','seventh rank rook pawn rook ending edge pawn',37),
('rook-connected-pawns','Rook vs Connected Passed Pawns','Rook','Rook vs pawns','Use checking geometry and king support to stop connected passers.','8/8/3pp3/8/8/3K4/8/R5k1 w - - 0 1',1700,2700,'Advanced','Connected passers can protect each other, so attacking one pawn may not be enough.','Use checks to force king placement, then attack the rear pawn or create a skewer along the rank.','rook vs connected passed pawns two pawns',38),
('queen-central-pawn','Queen vs Central Pawn','Queen','Queen vs pawn','Use checks and king approach to stop a central pawn near promotion.','8/4P3/8/8/8/8/5K2/7q b - - 0 1',1600,2600,'Club','The queen must check with a purpose while the king approaches.','Force the pawn’s king away or make the pawn block its own king, then bring your king closer.','queen vs central pawn queen pawn promotion',39),
('queen-rook-pawn','Queen vs Rook Pawn','Queen','Queen vs pawn','Handle the drawing tricks created by a rook pawn on the seventh rank.','8/7P/8/8/8/8/6K1/q7 b - - 0 1',1900,2800,'Advanced','Rook pawns create stalemate resources that central pawns do not.','Do not force the king into the corner without checking the stalemate geometry. Bring your king close at the right moment.','queen vs rook pawn stalemate seventh rank',40),
('queen-bishop-pawn','Queen vs Bishop Pawn','Queen','Queen vs pawn','Convert carefully against a bishop pawn on the seventh rank.','8/2P5/8/8/8/8/5K2/7q b - - 0 1',1800,2800,'Advanced','Bishop pawns have different stalemate patterns from central pawns.','Use checks to force the king onto the promotion square, then gain time for your own king to approach.','queen vs bishop pawn seventh rank',41),
('queen-knight-pawn','Queen vs Knight Pawn','Queen','Queen vs pawn','Use accurate checks against a knight pawn close to promotion.','8/1P6/8/8/8/8/5K2/7q b - - 0 1',1800,2800,'Advanced','The exact pawn file changes whether checking patterns produce stalemate.','Keep the pawn under control and improve your king without allowing promotion with check.','queen vs knight pawn seventh rank',42),
('queen-rook','Queen vs Rook: Precision Conversion','Queen','Queen vs rook','Force the rook away from its king and win it with zugzwang or a checking fork.','8/8/8/8/8/4KQ2/6rk/8 w - - 0 1',2300,3000,'Master','Queen versus rook is won, but accurate defense makes it difficult.','Improve the king, restrict the rook, and create a position where the rook must leave the king’s protection.','queen vs rook master zugzwang fork precision conversion',43),
('queen-rook-third','Queen vs Rook: Third-Rank Defense','Queen','Queen vs rook','Break the rook’s most stubborn defensive setup without allowing endless checks.','8/8/8/4K3/8/2r5/5Q2/7k w - - 0 1',2400,3000,'Master','The rook is using a compact defensive setup close to its king.','Do not chase checks. Improve the queen and king until the rook runs out of safe checking squares.','queen vs rook third rank defense master',44),
('queen-bishop','Queen vs Bishop','Queen','Queen vs minor piece','Use queen-and-king coordination to trap a bishop without stalemating the king.','8/8/8/4K3/8/2b5/5Q2/7k w - - 0 1',1700,2700,'Advanced','The queen dominates many squares, but the king is needed to finish the job.','Restrict the bishop and king together, then force a fork or mating net.','queen vs bishop minor piece conversion',45),
('queen-knight','Queen vs Knight','Queen','Queen vs minor piece','Restrict knight forks while using the queen and king to force a win.','8/8/8/4K3/8/2n5/5Q2/7k w - - 0 1',1800,2800,'Advanced','The knight’s fork squares are the main practical danger.','Keep checking squares controlled and bring the king close enough that queen checks also attack the knight.','queen vs knight fork conversion',46),
('queen-perpetual','Perpetual Check in Queen Endings','Queen','Queen endings','Recognize when repeated checks force a draw despite a material disadvantage.','8/8/6k1/8/5q2/7K/5P2/6Q1 b - - 0 1',2000,2900,'Expert','Queen endings are often decided by checking geometry rather than material.','Track escape squares and repetition. If the king cannot break the checking net without losing material, perpetual check may be the correct result.','perpetual check queen ending forced draw repetition',47),
('rook-bishop','Rook vs Bishop','Rook','Pawnless piece endings','Use king and rook coordination against a lone bishop while avoiding fortress setups.','8/8/8/4K3/8/2b5/5R2/6k1 w - - 0 1',1900,2800,'Advanced','Pawnless rook versus bishop is often about domination and king placement.','Cut the king off, limit the bishop’s diagonals, and avoid allowing the bishop to trade itself for the rook.','rook vs bishop pawnless domination',48),
('rook-knight','Rook vs Knight','Rook','Pawnless piece endings','Use the rook’s range to restrict a knight and coordinate with the king.','8/8/8/4K3/8/2n5/5R2/6k1 w - - 0 1',1900,2800,'Advanced','The knight wants a stable central square and fork opportunities.','Keep the rook at a safe distance and use the king to deny central outposts.','rook vs knight pawnless domination',49),
('rb-lolli','Lolli Position: Rook and Bishop vs Rook','Rook','Rook and bishop vs rook','Dominate the defending rook and force the king toward the edge.','1r6/8/8/8/2B5/2K5/6R1/2k5 b - - 0 1',2400,3000,'Master','This is one of the difficult winning setups in rook and bishop versus rook.','Coordinate rook, bishop, and king so the defender runs out of checks and useful rook squares.','lolli rook bishop vs rook master domination',50),
('rb-cochrane','Cochrane Defense: Rook and Bishop vs Rook','Rook','Rook and bishop vs rook','Use the defending rook actively to separate the attacking king from its bishop.','8/8/8/4k3/8/3B4/4RK2/7r b - - 0 1',2300,3000,'Master','The defender survives by staying active rather than waiting passively.','Check or pin along ranks and files so the attacking king cannot coordinate cleanly with the bishop.','cochrane defense rook bishop vs rook master draw',51),
('rb-philidor','Philidor Position: Rook and Bishop vs Rook','Rook','Rook and bishop vs rook','Coordinate the stronger pieces in the classic winning setup.','8/8/8/4k3/8/3B4/4RK2/6r1 w - - 0 1',2400,3000,'Master','This is the stronger side’s precision technique in rook and bishop versus rook.','Use the rook to cut the king and the bishop to deny escape squares before forcing the defending rook away.','philidor rook bishop vs rook master winning setup',52);
with base_insert as (
 insert into public.endgame_positions(title,category,subcategory,concept,fen,source_type,min_elo,max_elo,difficulty,objective,coach_intro,coach_lesson,published,owner_verified,search_aliases,concept_key,variant_no,curriculum_order)
 select title,category,subcategory,concept,fen,'theory',min_elo,max_elo,difficulty,'tablebase',coach_intro,coach_lesson,true,true,search_aliases,concept_key,1,sort_no from bozo_endgame_seed
 returning *
), cand as (
 select b.*,x.ord,x.vf from base_insert b cross join lateral (values
  (2,pg_temp.bozo_fen_variant(b.fen,'mirror')),
  (3,pg_temp.bozo_fen_variant(b.fen,'rot')),
  (4,pg_temp.bozo_fen_variant(b.fen,'vflip')),
  (5,pg_temp.bozo_shift_fen(b.fen,1)),
  (6,pg_temp.bozo_shift_fen(b.fen,-1)),
  (7,pg_temp.bozo_shift_fen(b.fen,2)),
  (8,pg_temp.bozo_shift_fen(b.fen,-2)),
  (9,pg_temp.bozo_shift_fen(pg_temp.bozo_fen_variant(b.fen,'rot'),1)),
  (10,pg_temp.bozo_shift_fen(pg_temp.bozo_fen_variant(b.fen,'rot'),-1))
 ) x(ord,vf) where x.vf is not null
), uniq as (select distinct on (concept_key,vf) * from cand order by concept_key,vf,ord)
insert into public.endgame_positions(title,category,subcategory,concept,fen,source_type,min_elo,max_elo,difficulty,objective,coach_intro,coach_lesson,published,owner_verified,search_aliases,concept_key,variant_no,curriculum_order)
select title||' — Training '||ord,category,subcategory,concept,vf,'theory',min_elo,max_elo,difficulty,'tablebase',coach_intro,coach_lesson,true,true,search_aliases||' '||replace(concept_key,'-',' ')||' training variant '||ord,concept_key,ord,(curriculum_order*10)+ord
from uniq on conflict (fen) do nothing;
