(() => {
  'use strict';
  const KEY='bozo_opening_mastery_v1';
  let session=null;
  const $=id=>document.getElementById(id);
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"openings":{},"bestStreak":0}') }catch{return {openings:{},bestStreak:0}}};
  const save=data=>localStorage.setItem(KEY,JSON.stringify(data));
  const rank=p=>p>=100?'BOZO Grandmaster':p>=80?'Master':p>=60?'Expert':p>=40?'Apprentice':p>=20?'Student':'Beginner';
  function get(id){const d=load();return d.openings[id]||{name:'Opening',maxPly:0,totalPlies:0,sessions:0,bestStreak:0,lastPracticed:null};}
  function percent(o){return o.totalPlies?Math.min(100,Math.round((o.maxPly/o.totalPlies)*100)):0;}
  function cardMarkup(id){const o=get(id),p=percent(o);return `<div class="opening-mastery-cardline"><span>${rank(p)}</span><div class="opening-mastery-track"><span style="width:${p}%"></span></div><strong>${p}%</strong></div>`}
  const compactMarkup=cardMarkup;
  function refreshAll(){document.querySelectorAll('[data-mastery-opening]').forEach(el=>{el.innerHTML=cardMarkup(el.dataset.masteryOpening)});renderDashboard();}
  function startSession(opening){session={id:String(opening.id),name:opening.name+(opening.variation?`: ${opening.variation}`:''),streak:0,best:0,completed:false};paintStudyPanel(opening,0,0)}
  function recordStudyPly(opening,ply,total,previous){if(!opening)return; if(!session||session.id!==String(opening.id))startSession(opening); if(ply===previous+1){session.streak++;session.best=Math.max(session.best,session.streak)}else if(ply<previous){session.streak=0}else if(ply>previous+1){session.streak=Math.max(session.streak,ply)}
    const d=load(),id=String(opening.id),o=d.openings[id]||{name:session.name,maxPly:0,totalPlies:total,sessions:0,bestStreak:0};o.name=session.name;o.totalPlies=Math.max(total,o.totalPlies||0);o.maxPly=Math.max(ply,o.maxPly||0);o.bestStreak=Math.max(o.bestStreak||0,session.best);o.lastPracticed=new Date().toISOString();d.bestStreak=Math.max(d.bestStreak||0,o.bestStreak);d.openings[id]=o;save(d);paintStudyPanel(opening,ply,total);refreshAll();
    if(total>0&&ply===total&&!session.completed){session.completed=true;o.sessions=(o.sessions||0)+1;d.openings[id]=o;save(d);showSummary(o,total);}
  }
  function paintStudyPanel(opening,ply,total){if(!opening)return;const o=get(String(opening.id));const effective={...o,totalPlies:total||o.totalPlies,maxPly:Math.max(o.maxPly||0,ply||0)};const p=percent(effective);if($('study-mastery-percent'))$('study-mastery-percent').textContent=`${p}%`;if($('study-mastery-rank'))$('study-mastery-rank').textContent=rank(p);if($('study-mastery-fill'))$('study-mastery-fill').style.width=`${p}%`;if($('study-session-streak'))$('study-session-streak').textContent=session?.streak||0;if($('study-best-streak'))$('study-best-streak').textContent=Math.max(o.bestStreak||0,session?.best||0);if($('study-mastery-note'))$('study-mastery-note').textContent=p===100?'Line completed. Repeat it later to reinforce the pattern.':`${Math.max(0,(total||0)-(ply||0))} plies remain in this walkthrough.`}
  function showSummary(o,total){const p=percent(o);$('mastery-summary-title').textContent=o.name;$('mastery-summary-percent').textContent=`${p}%`;$('mastery-summary-rank').textContent=rank(p);$('mastery-summary-moves').textContent=total;$('mastery-summary-streak').textContent=o.bestStreak||0;$('mastery-summary-sessions').textContent=o.sessions||1;$('mastery-summary-message').textContent=p===100?'You completed the full line. This opening is now marked as mastered locally.':'Good session. Continue through the remaining moves to raise mastery.';$('mastery-summary-modal').hidden=false;refreshAll()}
  function renderDashboard(){const d=load(),rows=Object.entries(d.openings).map(([id,o])=>({id,...o,p:percent(o)})).sort((a,b)=>b.p-a.p||String(b.lastPracticed).localeCompare(String(a.lastPracticed)));const overall=rows.length?Math.round(rows.reduce((s,o)=>s+o.p,0)/rows.length):0;if($('local-overall-mastery'))$('local-overall-mastery').textContent=`${overall}%`;if($('local-mastery-rank'))$('local-mastery-rank').textContent=rank(overall);if($('local-lines-studied'))$('local-lines-studied').textContent=rows.length;if($('local-best-streak'))$('local-best-streak').textContent=d.bestStreak||0;if($('local-needs-review'))$('local-needs-review').textContent=rows.filter(o=>o.p>0&&o.p<100).length;const list=$('local-mastery-list');if(!list)return;list.innerHTML=rows.length?rows.slice(0,12).map(o=>`<article class="local-mastery-row"><div><h3>${escapeHtml(o.name||'Opening')}</h3><small>${rank(o.p)} · ${o.sessions||0} sessions</small></div><div class="opening-mastery-track"><span style="width:${o.p}%"></span></div><strong>${o.p}%</strong></article>`).join(''):'<div class="empty-state"><div>♟</div><b>No local mastery yet</b><span>Open a line in the Opening Library and walk through its moves.</span></div>'}
  function reset(){if(!confirm('Reset all local opening mastery on this device?'))return;localStorage.removeItem(KEY);session=null;refreshAll();toast?.('Local mastery reset')}
  document.addEventListener('DOMContentLoaded',()=>{$('reset-local-mastery')?.addEventListener('click',reset);const close=()=>{$('mastery-summary-modal').hidden=true};$('close-mastery-summary')?.addEventListener('click',close);$('mastery-summary-done')?.addEventListener('click',close);$('mastery-summary-modal')?.addEventListener('click',e=>{if(e.target.id==='mastery-summary-modal')close()});renderDashboard()});
  window.BozoMastery={cardMarkup,compactMarkup,refreshAll,startSession,recordStudyPly,paintStudyPanel,renderDashboard,rank};
})();
