-- BOZO v4.14.0 — Master Games study/training foundation
-- Run once in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.bozo_master_games (
  id uuid primary key default gen_random_uuid(),
  game_key text not null unique,
  white text not null,
  black text not null,
  white_elo integer,
  black_elo integer,
  event text,
  site text,
  game_date date,
  game_year integer,
  round text,
  result text not null default '*',
  eco text,
  opening text,
  starting_fen text not null default 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  moves_san jsonb not null default '[]'::jsonb,
  moves_uci jsonb not null default '[]'::jsonb,
  move_count integer not null default 0,
  pgn text not null,
  source_label text not null default 'Public PGN',
  imported_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bozo_master_games_white_idx on public.bozo_master_games (lower(white));
create index if not exists bozo_master_games_black_idx on public.bozo_master_games (lower(black));
create index if not exists bozo_master_games_year_idx on public.bozo_master_games (game_year desc);
create index if not exists bozo_master_games_eco_idx on public.bozo_master_games (eco);
create index if not exists bozo_master_games_result_idx on public.bozo_master_games (result);

create table if not exists public.bozo_master_game_positions (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.bozo_master_games(id) on delete cascade,
  ply integer not null,
  fen text not null,
  fen_key text not null,
  san text not null,
  uci text not null,
  unique(game_id, ply)
);
create index if not exists bozo_master_positions_game_idx on public.bozo_master_game_positions(game_id, ply);
create index if not exists bozo_master_positions_fen_key_idx on public.bozo_master_game_positions(fen_key);

create table if not exists public.bozo_master_training_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  game_id uuid not null references public.bozo_master_games(id) on delete cascade,
  training_side text not null check (training_side in ('white','black','both')),
  master_matches integer not null default 0,
  alternative_moves integer not null default 0,
  total_decisions integer not null default 0,
  match_percent integer not null default 0,
  decisions jsonb not null default '[]'::jsonb,
  started_at timestamptz,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists bozo_master_training_user_idx on public.bozo_master_training_runs(user_id, created_at desc);
create index if not exists bozo_master_training_game_idx on public.bozo_master_training_runs(game_id, created_at desc);

alter table public.bozo_master_games enable row level security;
alter table public.bozo_master_game_positions enable row level security;
alter table public.bozo_master_training_runs enable row level security;

drop policy if exists "master games are public" on public.bozo_master_games;
create policy "master games are public" on public.bozo_master_games for select to anon, authenticated using (true);
drop policy if exists "owner imports master games" on public.bozo_master_games;
create policy "owner imports master games" on public.bozo_master_games for insert to authenticated with check (public.bozo_is_owner());
drop policy if exists "owner updates master games" on public.bozo_master_games;
create policy "owner updates master games" on public.bozo_master_games for update to authenticated using (public.bozo_is_owner()) with check (public.bozo_is_owner());
drop policy if exists "owner deletes master games" on public.bozo_master_games;
create policy "owner deletes master games" on public.bozo_master_games for delete to authenticated using (public.bozo_is_owner());

drop policy if exists "master positions are public" on public.bozo_master_game_positions;
create policy "master positions are public" on public.bozo_master_game_positions for select to anon, authenticated using (true);
drop policy if exists "owner imports master positions" on public.bozo_master_game_positions;
create policy "owner imports master positions" on public.bozo_master_game_positions for insert to authenticated with check (public.bozo_is_owner());
drop policy if exists "owner updates master positions" on public.bozo_master_game_positions;
create policy "owner updates master positions" on public.bozo_master_game_positions for update to authenticated using (public.bozo_is_owner()) with check (public.bozo_is_owner());
drop policy if exists "owner deletes master positions" on public.bozo_master_game_positions;
create policy "owner deletes master positions" on public.bozo_master_game_positions for delete to authenticated using (public.bozo_is_owner());

drop policy if exists "users read own master training" on public.bozo_master_training_runs;
create policy "users read own master training" on public.bozo_master_training_runs for select to authenticated using (user_id=auth.uid());
drop policy if exists "users save own master training" on public.bozo_master_training_runs;
create policy "users save own master training" on public.bozo_master_training_runs for insert to authenticated with check (user_id=auth.uid());
drop policy if exists "users delete own master training" on public.bozo_master_training_runs;
create policy "users delete own master training" on public.bozo_master_training_runs for delete to authenticated using (user_id=auth.uid());

create or replace function public.search_master_games(
  p_query text default null,
  p_year integer default null,
  p_result text default null,
  p_limit integer default 80
) returns setof public.bozo_master_games
language sql stable security definer set search_path=public as $$
  select g.*
  from public.bozo_master_games g
  where (p_query is null or btrim(p_query)='' or
         g.white ilike '%'||p_query||'%' or g.black ilike '%'||p_query||'%' or
         coalesce(g.event,'') ilike '%'||p_query||'%' or coalesce(g.opening,'') ilike '%'||p_query||'%' or
         coalesce(g.eco,'') ilike '%'||p_query||'%' or coalesce(g.site,'') ilike '%'||p_query||'%')
    and (p_year is null or g.game_year=p_year)
    and (p_result is null or btrim(p_result)='' or g.result=p_result)
  order by g.game_date desc nulls last, g.created_at desc
  limit least(greatest(coalesce(p_limit,80),1),200);
$$;

grant select on public.bozo_master_games to anon, authenticated;
grant select on public.bozo_master_game_positions to anon, authenticated;
grant select,insert,delete on public.bozo_master_training_runs to authenticated;
grant insert,update,delete on public.bozo_master_games to authenticated;
grant insert,update,delete on public.bozo_master_game_positions to authenticated;
grant execute on function public.search_master_games(text,integer,text,integer) to anon, authenticated;


-- v4.14.1 integration helpers
create or replace function public.master_database_stats()
returns table(game_count bigint, position_count bigint, newest_game date, oldest_game date)
language sql stable security definer set search_path=public as $$
  select (select count(*) from public.bozo_master_games),
         (select count(*) from public.bozo_master_game_positions),
         (select max(game_date) from public.bozo_master_games),
         (select min(game_date) from public.bozo_master_games);
$$;
grant execute on function public.master_database_stats() to anon, authenticated;

create or replace function public.master_games_reaching_position(p_fen_key text, p_limit integer default 80)
returns setof public.bozo_master_games
language sql stable security definer set search_path=public as $$
  select g.* from public.bozo_master_games g
  where exists (select 1 from public.bozo_master_game_positions p where p.game_id=g.id and p.fen_key=p_fen_key)
  order by g.game_date desc nulls last, g.created_at desc
  limit least(greatest(coalesce(p_limit,80),1),200);
$$;
grant execute on function public.master_games_reaching_position(text,integer) to anon, authenticated;
