-- BOZO v4.13.0 Connect: private DMs, Ask BOZO, notifications, blocks/reports
create extension if not exists pgcrypto;

create table if not exists public.bozo_dm_threads (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.bozo_dm_participants (thread_id uuid references public.bozo_dm_threads(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, joined_at timestamptz not null default now(), last_read_at timestamptz, primary key(thread_id,user_id));
create table if not exists public.bozo_dm_messages (id bigint generated always as identity primary key, thread_id uuid references public.bozo_dm_threads(id) on delete cascade not null, sender_id uuid references auth.users(id) on delete cascade not null, body text not null check(char_length(body) between 1 and 4000), created_at timestamptz not null default now());
create table if not exists public.bozo_user_blocks (blocker_id uuid references auth.users(id) on delete cascade, blocked_id uuid references auth.users(id) on delete cascade, created_at timestamptz default now(), primary key(blocker_id,blocked_id));
create table if not exists public.bozo_dm_reports (id bigint generated always as identity primary key, reporter_id uuid references auth.users(id) on delete cascade not null, thread_id uuid references public.bozo_dm_threads(id) on delete cascade not null, reason text not null, status text not null default 'open', created_at timestamptz default now());
create table if not exists public.bozo_support_threads (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade not null, username text, subject text not null, status text not null default 'open', context jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.bozo_support_messages (id bigint generated always as identity primary key, thread_id uuid references public.bozo_support_threads(id) on delete cascade not null, sender_id uuid references auth.users(id) on delete cascade not null, body text not null check(char_length(body) between 1 and 4000), created_at timestamptz default now());
create table if not exists public.bozo_notifications (id bigint generated always as identity primary key, user_id uuid references auth.users(id) on delete cascade not null, kind text not null default 'general', title text not null, body text, route text, read_at timestamptz, created_at timestamptz default now());
create index if not exists bozo_dm_messages_thread_idx on public.bozo_dm_messages(thread_id,created_at);
create index if not exists bozo_support_messages_thread_idx on public.bozo_support_messages(thread_id,created_at);
create index if not exists bozo_notifications_user_idx on public.bozo_notifications(user_id,created_at desc);

alter table public.bozo_dm_threads enable row level security; alter table public.bozo_dm_participants enable row level security; alter table public.bozo_dm_messages enable row level security; alter table public.bozo_user_blocks enable row level security; alter table public.bozo_dm_reports enable row level security; alter table public.bozo_support_threads enable row level security; alter table public.bozo_support_messages enable row level security; alter table public.bozo_notifications enable row level security;

drop policy if exists dm_participant_threads on public.bozo_dm_threads; create policy dm_participant_threads on public.bozo_dm_threads for select using(exists(select 1 from public.bozo_dm_participants p where p.thread_id=id and p.user_id=auth.uid()));
drop policy if exists dm_participants_self on public.bozo_dm_participants; create policy dm_participants_self on public.bozo_dm_participants for select using(user_id=auth.uid() or exists(select 1 from public.bozo_dm_participants p where p.thread_id=bozo_dm_participants.thread_id and p.user_id=auth.uid()));
drop policy if exists dm_messages_read on public.bozo_dm_messages; create policy dm_messages_read on public.bozo_dm_messages for select using(exists(select 1 from public.bozo_dm_participants p where p.thread_id=bozo_dm_messages.thread_id and p.user_id=auth.uid()));
drop policy if exists dm_messages_send on public.bozo_dm_messages; create policy dm_messages_send on public.bozo_dm_messages for insert with check(sender_id=auth.uid() and exists(select 1 from public.bozo_dm_participants p where p.thread_id=bozo_dm_messages.thread_id and p.user_id=auth.uid()) and not exists(select 1 from public.bozo_dm_participants me join public.bozo_dm_participants them on them.thread_id=me.thread_id and them.user_id<>me.user_id join public.bozo_user_blocks b on (b.blocker_id=them.user_id and b.blocked_id=me.user_id) or (b.blocker_id=me.user_id and b.blocked_id=them.user_id) where me.thread_id=bozo_dm_messages.thread_id and me.user_id=auth.uid()));
drop policy if exists blocks_self on public.bozo_user_blocks; create policy blocks_self on public.bozo_user_blocks for all using(blocker_id=auth.uid()) with check(blocker_id=auth.uid());
drop policy if exists reports_insert on public.bozo_dm_reports; create policy reports_insert on public.bozo_dm_reports for insert with check(reporter_id=auth.uid() and exists(select 1 from public.bozo_dm_participants p where p.thread_id=bozo_dm_reports.thread_id and p.user_id=auth.uid()));
drop policy if exists reports_own on public.bozo_dm_reports; create policy reports_own on public.bozo_dm_reports for select using(reporter_id=auth.uid());

-- Staff means explicit moderation/support roles, not automatic access to private DMs.
create or replace function public.bozo_is_staff(uid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.user_roles where user_id=uid and role in ('owner','administrator','senior_moderator','moderator'))$$;
drop policy if exists support_threads_read on public.bozo_support_threads; create policy support_threads_read on public.bozo_support_threads for select using(user_id=auth.uid() or public.bozo_is_staff(auth.uid()));
drop policy if exists support_threads_insert on public.bozo_support_threads; create policy support_threads_insert on public.bozo_support_threads for insert with check(user_id=auth.uid());
drop policy if exists support_messages_read on public.bozo_support_messages; create policy support_messages_read on public.bozo_support_messages for select using(exists(select 1 from public.bozo_support_threads t where t.id=thread_id and (t.user_id=auth.uid() or public.bozo_is_staff(auth.uid()))));
drop policy if exists support_messages_insert on public.bozo_support_messages; create policy support_messages_insert on public.bozo_support_messages for insert with check(sender_id=auth.uid() and exists(select 1 from public.bozo_support_threads t where t.id=thread_id and (t.user_id=auth.uid() or public.bozo_is_staff(auth.uid()))));
drop policy if exists notifications_self on public.bozo_notifications; create policy notifications_self on public.bozo_notifications for select using(user_id=auth.uid());
drop policy if exists notifications_update_self on public.bozo_notifications; create policy notifications_update_self on public.bozo_notifications for update using(user_id=auth.uid());

create or replace function public.bozo_get_or_create_dm(target_username text) returns uuid language plpgsql security definer set search_path=public as $$declare target uuid; tid uuid; begin select id into target from profiles where lower(username)=lower(target_username) limit 1; if target is null then raise exception 'Player not found'; end if; if target=auth.uid() then raise exception 'You cannot message yourself'; end if; if exists(select 1 from bozo_user_blocks where (blocker_id=auth.uid() and blocked_id=target) or (blocker_id=target and blocked_id=auth.uid())) then raise exception 'Messaging is unavailable for this player'; end if; select a.thread_id into tid from bozo_dm_participants a join bozo_dm_participants b on b.thread_id=a.thread_id where a.user_id=auth.uid() and b.user_id=target and (select count(*) from bozo_dm_participants c where c.thread_id=a.thread_id)=2 limit 1; if tid is null then insert into bozo_dm_threads default values returning id into tid; insert into bozo_dm_participants(thread_id,user_id) values(tid,auth.uid()),(tid,target); end if; return tid; end$$;
create or replace function public.bozo_my_dm_threads() returns table(thread_id uuid,other_username text,last_message text,last_message_at timestamptz) language sql security definer set search_path=public as $$select t.id,p.username,(select m.body from bozo_dm_messages m where m.thread_id=t.id order by m.created_at desc limit 1),(select m.created_at from bozo_dm_messages m where m.thread_id=t.id order by m.created_at desc limit 1) from bozo_dm_threads t join bozo_dm_participants me on me.thread_id=t.id and me.user_id=auth.uid() join bozo_dm_participants op on op.thread_id=t.id and op.user_id<>auth.uid() left join profiles p on p.id=op.user_id order by coalesce((select max(m.created_at) from bozo_dm_messages m where m.thread_id=t.id),t.created_at) desc$$;
create or replace function public.bozo_create_support_thread(p_subject text,p_message text,p_context jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare tid uuid; uname text; begin select username into uname from profiles where id=auth.uid(); insert into bozo_support_threads(user_id,username,subject,context) values(auth.uid(),uname,p_subject,p_context) returning id into tid; insert into bozo_support_messages(thread_id,sender_id,body) values(tid,auth.uid(),p_message); return tid; end$$;
create or replace function public.bozo_block_dm_thread(p_thread_id uuid) returns void language plpgsql security definer set search_path=public as $$declare other uuid; begin select user_id into other from bozo_dm_participants where thread_id=p_thread_id and user_id<>auth.uid() limit 1; if other is null or not exists(select 1 from bozo_dm_participants where thread_id=p_thread_id and user_id=auth.uid()) then raise exception 'Conversation not found'; end if; insert into bozo_user_blocks(blocker_id,blocked_id) values(auth.uid(),other) on conflict do nothing; end$$;
create or replace function public.bozo_report_dm_thread(p_thread_id uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from bozo_dm_participants where thread_id=p_thread_id and user_id=auth.uid()) then raise exception 'Conversation not found'; end if; insert into bozo_dm_reports(reporter_id,thread_id,reason) values(auth.uid(),p_thread_id,p_reason); end$$;
create or replace function public.bozo_unread_dm_count() returns bigint language sql security definer set search_path=public as $$select count(*) from bozo_dm_messages m join bozo_dm_participants me on me.thread_id=m.thread_id and me.user_id=auth.uid() where m.sender_id<>auth.uid() and m.created_at>coalesce(me.last_read_at,'epoch'::timestamptz)$$;
create or replace function public.bozo_unread_support_count() returns bigint language sql security definer set search_path=public as $$select count(*) from bozo_support_messages m join bozo_support_threads t on t.id=m.thread_id where ((t.user_id=auth.uid() and m.sender_id<>auth.uid()) or (public.bozo_is_staff(auth.uid()) and m.sender_id=t.user_id))$$;

grant execute on function public.bozo_get_or_create_dm(text) to authenticated; grant execute on function public.bozo_my_dm_threads() to authenticated; grant execute on function public.bozo_create_support_thread(text,text,jsonb) to authenticated; grant execute on function public.bozo_block_dm_thread(uuid) to authenticated; grant execute on function public.bozo_report_dm_thread(uuid,text) to authenticated; grant execute on function public.bozo_unread_dm_count() to authenticated; grant execute on function public.bozo_unread_support_count() to authenticated;

-- Create in-site alerts automatically. Message bodies are deliberately not copied into notification text.
create or replace function public.bozo_notify_dm() returns trigger language plpgsql security definer set search_path=public as $$begin insert into bozo_notifications(user_id,kind,title,body,route) select p.user_id,'dm','New message','A BOZO player sent you a message.','#friends' from bozo_dm_participants p where p.thread_id=new.thread_id and p.user_id<>new.sender_id; update bozo_dm_threads set updated_at=now() where id=new.thread_id; return new; end$$;
drop trigger if exists bozo_dm_notify on public.bozo_dm_messages; create trigger bozo_dm_notify after insert on public.bozo_dm_messages for each row execute function public.bozo_notify_dm();
create or replace function public.bozo_notify_support() returns trigger language plpgsql security definer set search_path=public as $$declare owner_id uuid; asker uuid; begin select user_id into asker from bozo_support_threads where id=new.thread_id; update bozo_support_threads set updated_at=now() where id=new.thread_id; if new.sender_id=asker then insert into bozo_notifications(user_id,kind,title,body,route) select ur.user_id,'support','New Ask BOZO question','A player is waiting for a reply.','#support' from user_roles ur where ur.role in ('owner','administrator','senior_moderator','moderator'); else insert into bozo_notifications(user_id,kind,title,body,route) values(asker,'support','BOZO replied','Your Ask BOZO conversation has a new reply.','#support'); end if; return new; end$$;
drop trigger if exists bozo_support_notify on public.bozo_support_messages; create trigger bozo_support_notify after insert on public.bozo_support_messages for each row execute function public.bozo_notify_support();
