-- BOZO v2.7.0 Connected Experience
-- Run once in Supabase SQL Editor AFTER deploying, or immediately before deployment.

create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_type text not null check (activity_type in (
    'opening_studied',
    'game_reviewed',
    'profile_updated',
    'friend_added',
    'suggestion_submitted',
    'challenge_completed'
  )),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_activity_user_created_idx
  on public.user_activity (user_id, created_at desc);

alter table public.user_activity enable row level security;

drop policy if exists "users read own activity" on public.user_activity;
create policy "users read own activity"
  on public.user_activity
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "users create own activity" on public.user_activity;
create policy "users create own activity"
  on public.user_activity
  for insert
  to authenticated
  with check (auth.uid() = user_id);

revoke all on table public.user_activity from anon;
grant select, insert on table public.user_activity to authenticated;
grant usage, select on sequence public.user_activity_id_seq to authenticated;

-- Friend-only summary used by the expanded profile modal.
create or replace function public.get_friend_activity_summary(target_username text)
returns table (
  openings_studied bigint,
  games_reviewed bigint,
  accepted_suggestions bigint,
  member_since timestamptz,
  recent_activity jsonb
)
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  target_id uuid;
begin
  select p.id into target_id
  from public.profiles p
  where lower(p.username) = lower(trim(leading '@' from target_username))
    and exists (
      select 1
      from public.my_friends() f
      where lower(f.username) = lower(trim(leading '@' from target_username))
        and f.status = 'accepted'
    )
  limit 1;

  if target_id is null then
    return;
  end if;

  return query
  select
    (select count(distinct nullif(a.payload->>'opening_id', ''))
       from public.user_activity a
      where a.user_id = target_id and a.activity_type = 'opening_studied')::bigint,
    (select count(*)
       from public.user_activity a
      where a.user_id = target_id and a.activity_type = 'game_reviewed')::bigint,
    (select count(*)
       from public.opening_submissions os
      where os.submitted_by = target_id
        and os.status in ('approved', 'accepted', 'published'))::bigint,
    (select p.created_at from public.profiles p where p.id = target_id),
    coalesce((
      select jsonb_agg(jsonb_build_object(
        'activity_type', recent.activity_type,
        'payload', recent.payload,
        'created_at', recent.created_at
      ) order by recent.created_at desc)
      from (
        select a.activity_type, a.payload, a.created_at
        from public.user_activity a
        where a.user_id = target_id
          and a.activity_type in ('opening_studied', 'game_reviewed', 'suggestion_submitted', 'challenge_completed')
        order by a.created_at desc
        limit 5
      ) recent
    ), '[]'::jsonb);
end;
$$;

revoke all on function public.get_friend_activity_summary(text) from public;
grant execute on function public.get_friend_activity_summary(text) to authenticated;
